// Generated by https://quicktype.io

export interface Tunnels {
  tunnels:       Tunnel[];
  uri:           string;
  next_page_uri: null;
}

export interface Tunnel {
  id:             string;
  public_url:     string;
  started_at:     string;
  proto:          string;
  region:         string;
  tunnel_session: Endpoint;
  endpoint:       Endpoint;
  forwards_to:    string;
}

export interface Endpoint {
  id:  string;
  uri: string;
}
