name: aaaa test
run-name: sukaaaa rabotay
on: 
  push:
    branches:
      - master
jobs:
  first-test-job:
      runs-on: ubuntu-latest
      steps:
        - name: say AAA
          run: |
            echo "AAA"
        - name: say something else
          env: 
            var1: something
            var2: else
          run: |
            echo $var1 $var2
        - name: hz che eto takoe
          uses: actions/checkout@v3 

      
